export const GETBLOGS_LOADING= 'GETBLOGS_LOADING';
export const GETBLOGS_ERROR= 'GETBLOGS_ERROR';
export const GETBLOGS_SUCCESS= 'GETBLOGS_SUCCESS';

export const ADDBLOG_LOADING= 'ADDBLOG_LOADING';
export const ADDBLOG_ERROR= 'ADDBLOG_ERROR';
export const ADDBLOG_SUCCESS= 'ADDBLOG_SUCCESS';


export const DELETEBLOG_LOADING= 'DELETEBLOG_LOADING';
export const DELETEBLOG_ERROR= 'DELETEBLOG_ERROR';
export const DELETEBLOG_SUCCESS= 'DELETEBLOG_SUCCESS';

export const ADDLIKE_LOADING= 'ADDLIKE_LOADING';
export const ADDLIKE_ERROR= 'ADDLIKE_ERROR';
export const ADDLIKE_SUCCESS= 'ADDLIKE_SUCCESS';

export const ADDCOMMENT_LOADING= 'ADDCOMMENT_LOADING';
export const ADDCOMMENT_ERROR= 'ADDCOMMENT_ERROR';
export const ADDCOMMENT_SUCCESS= 'ADDCOMMENT_SUCCESS';